// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKH14e51W7SmFnnEJqGRat8doiRJKvC_A',
    appId: '1:929400296914:web:e0541ab191582e615aa40b',
    messagingSenderId: '929400296914',
    projectId: 'todo-app-c9-91978',
    authDomain: 'todo-app-c9-91978.firebaseapp.com',
    storageBucket: 'todo-app-c9-91978.appspot.com',
    measurementId: 'G-HC3VM4WJPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhym7QCyxGuh2S6eCzM_D-xaw2x9PUA6Q',
    appId: '1:929400296914:android:d5ec7357f84e68315aa40b',
    messagingSenderId: '929400296914',
    projectId: 'todo-app-c9-91978',
    storageBucket: 'todo-app-c9-91978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCibKdQkFqUux4eSU1Y8m6kw9OfN3eV8hQ',
    appId: '1:929400296914:ios:2d4c0259fedd52da5aa40b',
    messagingSenderId: '929400296914',
    projectId: 'todo-app-c9-91978',
    storageBucket: 'todo-app-c9-91978.appspot.com',
    iosClientId:
        '929400296914-4l2g3nedm50nembilduhhtrgh0e7ansl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCibKdQkFqUux4eSU1Y8m6kw9OfN3eV8hQ',
    appId: '1:929400296914:ios:20d9fbd0641a49f25aa40b',
    messagingSenderId: '929400296914',
    projectId: 'todo-app-c9-91978',
    storageBucket: 'todo-app-c9-91978.appspot.com',
    iosClientId:
        '929400296914-9iv8c88q7nhbciglc5jj4t0g0q9govvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
